services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: projetos_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_rails:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rails:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: "1234"
    command: >
      bash -c "rails db:create db:migrate && rails server -b 0.0.0.0 -p 3001"

volumes:
  postgres_rails:
